### ISSUE TITLE
Style Survey - Come up with questions

### ISSUE THREAD

**Issue by sarynm12** [Atos20/Crate#11]
What specific questions do we want to ask our user?
How many questions?
What else do we need? (images, etc.)

**Comment by npdarrington** [comment]
I would highly recommend visiting [Stitchfix](https://www.stitchfix.com/onboarding/welcome-back/), creating an account and going through their survey to get a good feel for what it would be like for Crate. It sounds like we have landed on staying with clothing. Let's decide on some themes for Crates (date night, every day, athletic wear, business casual, professional dress, etc...) for categories and we can update crates and find images. Orlando and I have thought about asking Robbie a question during our check in today about how we can possible stream line this process.
