### ISSUE TITLE
Data Flow Chart Deliverable

### ISSUE THREAD

**Issue by npdarrington** [Atos20/Crate#7]
- [ ] Create a data flow chart or diagram that shows the data flow of track related to the current flow of the project.

This deliverable due date is Monday Dec 7.

**Comment by dhalverson** [comment]
BE flow chart

https://miro.com/app/board/o9J_lcPRYnE=/

**Comment by npdarrington** [comment]
FE Flow Chart

<img width="451" alt="Screen Shot 2020-12-05 at 12 44 25 PM" src="https://user-images.githubusercontent.com/59422609/101380657-07e86f80-3873-11eb-81ed-1fcf619acc58.png">

**Comment by npdarrington** [comment]
[Updated Flow Chart FE](https://miro.com/app/board/o9J_lcWlmFM=/). This will close this issue for now and will be updated as we further figure out the them with more solid information.
